apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: yolov8
  namespace: kubeflow-user-example-com
spec:
  predictor:
    serviceAccountName: sa-minio-kserve
    model:
      modelFormat:
        name: pytorch
      storageUri: "s3://mlpipeline/config/model-store/yolo_model.mar"
      protocolVersion: "v2"
      env:
        - name: TS_CONFIG_PATH
          value: /mnt/config/config.properties
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "4Gi"