apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../manifests/common/istio-1-23/kubeflow-istio-resources/base
- cluster-issuer.yaml
- kubeflow-certificate.yaml

# patches:
# - patch: |-
#     apiVersion: networking.istio.io/v1
#     kind: Gateway
#     metadata:
#       name: kubeflow-gateway
#       namespace: kubeflow
#     spec:
#       selector:
#         istio: ingressgateway
#       servers:
#       - hosts:
#         - '*'
#         port:
#           name: http
#           number: 80
#           protocol: HTTP
#       - hosts:
#         - '*' 
#         port:
#           name: https
#           number: 443
#           protocol: HTTPS
#         tls:
#           mode: SIMPLE
#           credentialName: kubeflow-tls
#   target:
#     kind: Gateway
#     name: kubeflow-gateway
#     namespace: kubeflow