apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../manifests/apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DISABLE_GKE_METADATA
        value: "true"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ARGO_ARCHIVE_LOGS
        value: "true"
  target:
    group: apps
    version: v1
    kind: Deployment
    name: ml-pipeline-ui
    namespace: kubeflow